### PR TITLE
Fix a soundness issue around separability

### LINKED ISSUE #5502: Type definitions with `constraint` can create non-separable types that are considered separable
Following the example from [this talk](https://youtu.be/It0i9xFqCtE?si=ZAJ1zohRr9kqQnW-&t=1256), the compiler currently assumes that any abstract type definition of the form `type ('a : value mod non_float) t` is separable since there is no way to define such a `t` that can have the same representation as `float`.

However, the same is *not* true when `constraint`s are involved. Given
```ml
type ('a : value mod non_float) t constraint 'a = 'b list
````
`float list t` *is* equal to `float` and therefore `t` is not actually separable even though the compiler incorrectly classifies it as such.

The following causes a segmentation fault on oxcaml 5.2.0+ox

```ml
module M : sig
  type ('a : value mod non_float) t constraint 'a = 'b list

  val float_t : float list t
  val non_float_t : int list t
end = struct
  type 'a t = 'b constraint 'a = 'b list

  let float_t : float list t = 5.0
  let non_float_t : int list t = 5
end

type t = K : 'a M.t -> t [@@unboxed]

let disaster = [| K M.float_t; K M.non_float_t |]
```

### PR DESCRIPTION
**Pull request by goldfirere**
Fixes #5502.

See the comment (also written by Claude) in typedecl_separability.ml.

I wrote the first commit, which segfaults if you run the test.

Claude wrote the second commit, which I have reviewed carefully.

Review: @dkalinichenko-js

### CODE REVIEW

**Comment by dkalinichenko-js** [comment]
Oof. I guess we never caught it because we don't use constraints at all.

File: testsuite/tests/typing-unboxed-types/test_flat.ml [hunk 1]
```diff
@@ -17,10 +17,17 @@ Error: This type cannot be unboxed because
        You should annotate it with "[@@ocaml.boxed]".
 |}];;
 
-(* accept since [list] is always non-float *)
+(* reject: [abs] could be implemented as a GADT that extracts the list
+   element type, e.g. [type _ abs = A : 'b -> 'b list abs [@@unboxed]] *)
 type t18 = A : _ list abs -> t18 [@@ocaml.unboxed];;
```
Comment (dkalinichenko-js) [inline testsuite/tests/typing-unboxed-types/test_flat.ml:22]: Oof, this one might actually have occured.

Comment (goldfirere) [reply testsuite/tests/typing-unboxed-types/test_flat.ml:22]: Yep. That's a good point. I'll keep an eye for regressions in the tree.
